default: &DEFAULT
  num_epochs: 100
  batch_size: 256


################big_net
ae_3_01_big:
    <<: *DEFAULT
    model_name: ae_3
    checkpoint_dir: "checkpoints/ae_3"
    log_dir: 'logs/logs_ae_3'
    gpu_vis_dev: '2'
    num_epochs: 30
    batch_size: 256
    lr: 0.001
    l1_factor:

#-----------------------------------
ae_3_l1_01_big:
    <<: *DEFAULT
    model_name: ae_3_l1
    checkpoint_dir: "checkpoints/ae_3_l1"
    log_dir: 'logs/logs_ae_3_l1'
    gpu_vis_dev: '2'
    num_epochs: 30
    batch_size: 256
    lr: 0.001
    l1_factor: 0.001
#-----------------------------------
ae_1_01_big:
  <<: *DEFAULT
  model_name: ae_1
  checkpoint_dir: "checkpoints/ae_1"
  log_dir: 'logs/logs_ae_1'
  gpu_vis_dev: '2'
  num_epochs: 30
  batch_size: 256
  lr: 0.001
  l1_factor:
#-----------------------------------
ae_1_l1_01_big:
  <<: *DEFAULT
  model_name: ae_1_l1
  checkpoint_dir: "checkpoints/ae_1_l1"
  log_dir: 'logs/logs_ae_1_l1'
  gpu_vis_dev: '2'
  num_epochs: 30
  batch_size: 256
  lr: 0.001
  l1_factor: 0.001
#-----------------------------------
ae_2_01_big:
   <<: *DEFAULT
   model_name: ae_2
   checkpoint_dir: "checkpoints/ae_2"
   log_dir: 'logs/logs_ae_2'
   gpu_vis_dev: '2'
   num_epochs: 30
   batch_size: 256
   lr: 0.001
   l1_factor:
#-----------------------------------
ae_2_l1_01_big:
   <<: *DEFAULT
   model_name: ae_2_l1
   checkpoint_dir: "checkpoints/ae_2_l1"
   log_dir: 'logs/logs_ae_2_l1'
   gpu_vis_dev: '2'
   num_epochs: 30
   batch_size: 256
   lr: 0.001
   l1_factor: 0.001
   

################small_net
ae_3_01_small:
    <<: *DEFAULT
    model_name: ae_3
    checkpoint_dir: "checkpoints/ae_3"
    log_dir: 'logs/logs_ae_3'
    gpu_vis_dev: '2'
    num_epochs: 100
    batch_size: 256
    lr: 0.01
    l1_factor:

#-----------------------------------

ae_3_l1_01_small:
    <<: *DEFAULT
    model_name: ae_3_l1
    checkpoint_dir: "checkpoints/ae_3_l1"
    log_dir: 'logs/logs_ae_3_l1'
    gpu_vis_dev: '2'
    num_epochs: 100
    batch_size: 256
    lr: 0.01
    l1_factor: 0.001
#-----------------------------------

ae_1_01_small:
  <<: *DEFAULT
  model_name: ae_1
  checkpoint_dir: "checkpoints/ae_1"
  log_dir: 'logs/logs_ae_1'
  gpu_vis_dev: '2'
  num_epochs: 100
  batch_size: 256
  lr: 0.01
  l1_factor:
#-----------------------------------

ae_1_l1_01_small:
  <<: *DEFAULT
  model_name: ae_1_l1
  checkpoint_dir: "checkpoints/ae_1_l1"
  log_dir: 'logs/logs_ae_1_l1'
  gpu_vis_dev: '2'
  num_epochs: 100
  batch_size: 256
  lr: 0.01
  l1_factor: 0.001
#-----------------------------------

ae_2_01_small:
   <<: *DEFAULT
   model_name: ae_2
   checkpoint_dir: "checkpoints/ae_2"
   log_dir: 'logs/logs_ae_2'
   gpu_vis_dev: '2'
   num_epochs: 100
   batch_size: 256
   lr: 0.01
   l1_factor:
#-----------------------------------

ae_2_l1_01_small:
   <<: *DEFAULT
   model_name: ae_2_l1
   checkpoint_dir: "checkpoints/ae_2_l1"
   log_dir: 'logs/logs_ae_2_l1'
   gpu_vis_dev: '2'
   num_epochs: 100
   batch_size: 256
   lr: 0.01
   l1_factor: 0.001
   
